import request from '../login'
Page({
  close:function(){
    wx.switchTab({
      url: '/pages/body/body',
    })
  },
  // 第一步下一步
  next1:function(){
    this.setData({
      img2:true,
      img1:false,
    })
  },
  // 第二部下一步
  next2:function(){
    this.setData({
      img2:false,
      img3:true,
    })
  },
  next3:function(){
    this.setData({
      img3:false,
      img4:true
    })
  },
  next4:function(){
    this.setData({
      img4:false,
      img5:true
    })
  },
  next5:function(){
    this.setData({
      img5:false,
      img6:true
    })
  },
  next6:function(){
    this.setData({
      img6:false,
      img7:true
    })
  },
  next7:function(){
    this.setData({
      img7:false,
      img8:true
    })
  },
  next8:function(){
    this.setData({
      img8:false,
      img9:true
    })
  },
  next9:function(){
    this.setData({
      img9:false,
      img10:true
    })
  },
  next10:function(){
    this.setData({
      img10:false,
      img11:true
    })
  },
  next11:function(){
    this.setData({
      img11:false,
      img12:true
    })
  },
  next12:function(){
    this.setData({
      img12:false,
      img13:true
    })
  },
  next13:function(){
    wx.switchTab({
      url: '/pages/body/body',
    })
  },

  // 第二步上一步
  up2:function(){
    this.setData({
      img1:true,
      img2:false
    })
  },
  // 第二部上一步
  up3:function(){
    this.setData({
      img2:true,
      img3:false,
    })
  },
  up4:function(){
    this.setData({
      img3:true,
      img4:false,
    })
  },
  up5:function(){
    this.setData({
      img4:true,
      img5:false,
    })
  },
  up6:function(){
    this.setData({
      img5:true,
      img6:false,
    })
  },
  up7:function(){
    this.setData({
      img6:true,
      img7:false,
    })
  },
  up8:function(){
    this.setData({
      img7:true,
      img8:false,
    })
  },
  up9:function(){
    this.setData({
      img8:true,
      img9:false,
    })
  },
  up10:function(){
    this.setData({
      img9:true,
      img10:false,
    })
  },
  up11:function(){
    this.setData({
      img10:true,
      img11:false,
    })
  },
  up12:function(){
    this.setData({
      img11:true,
      img12:false,
    })
  },
  up13:function(){
    this.setData({
      img12:true,
      img13:false,
    })
  },
  data:{
    img1:true,
  },
})